-- AD SOYAD : MELIKA JIBRIL SEID
-- OĞRENCİ NO: 23435004013
-- EMAIL: m3likaj@gmail.com


SELECT
    B.BOOKING_ID,
    T.TENANT_ID,
    T.FIRST_NAME,
    T.LAST_NAME,
    H.BLOCK_ID,
    H.HOUSE_NO,
    B.CA_NAME,
    B.REASON,
    BS.BOOKING_STATUS
FROM
    
    TENANT AS T
    JOIN HOUSE AS H ON H.HOUSE_ID = T.HOUSE_ID
	JOIN BOOKING AS B ON B.TENANT_ID = T.TENANT_ID
    JOIN BOOKING_STATUS AS BS ON BS.BOOKING_ID= B.BOOKING_ID
    
    WHERE BS.BOOKING_STATUS = 'confirmed'


-- YUKARIDAKİ SORGU RESERVE EDILEN ALANLARI VE RESERVASYON YAPAN KİŞİLERİ
-- DETAYLARI İLE BİRLİKTE LİSTELEMEKTEDİR. BU SORGUDA INNER, LEFT VE RIGHT JOIN
-- AYNI SONUCU VERİR


SELECT
    T.TENANT_ID,
    T.FIRST_NAME,
    T.LAST_NAME,
    H.HOUSE_NO,
    B.BLOCK_NO,
    UB.UTILITY_NAME,
    UB.BILL_AMOUNT,
    HP.PAYMENT_TYPE AS RENT_MORGAGE,
    HP.AMOUNT
FROM
    TENANT AS T
    LEFT JOIN HOUSE AS H ON T.HOUSE_ID = H.HOUSE_ID
    LEFT JOIN BLOCK AS B ON B.BLOCK_ID = H.BLOCK_ID
    LEFT JOIN UTILITY_BILL AS UB ON UB.TENANT_ID = T.TENANT_ID
    LEFT JOIN HOUSE_PAYMENTS AS HP ON UB.TENANT_ID = HP.TENANT_ID
WHERE
    HP.IS_PAID = 0 
    
    --YUKARIDAKI SORGU KIMLERİN ÖDENMEMİŞ KİRA VE FATURA OLDUĞUNU LİSTELEYEN BİR SORUGUDUR